### PR TITLE
Universal framework (iOS, macOS and tvOS) and SPM support

### PR DESCRIPTION
**Pull request by arturgrigor**
- Created a single target with support for iOS, macOS and tvOS
- Added support for Swift Package Manager

### CODE REVIEW

**Comment by arturgrigor** [comment]
Needs testing on iOS < 13.4 because I've set the iOS Deployment Target to be 10.0 but the OpenSSL framework was built for a newer version (13.4)

**Comment by arturgrigor** [comment]
Also, the macOS version of the OpenSSL.framework is not code signed at all and this breaks builds for macOS apps with the `code object is not signed at all` error message.

**Comment by lightsprint09** [comment]
Great work! SPM is the way into the future. 

I did a test run. I added your version to my projects which has a iOS Target and a Mac Target (Mac Catalyst). iOS compiles fine, but Mac shows the following error:

Bildschirmfoto 2020-09-05 um 16 44 49

**Comment by arturgrigor** [comment]
@lightsprint09 Should be fixed now.

**Comment by lightsprint09** [comment]
> @lightsprint09 Should be fixed now.

That was fast. Works, Thanks

**Comment by hannesoid** [comment]
thanks @arturgrigor!  having a look at this now…

**Comment by hannesoid** [comment]
@arturgrigor thanks a lot for you efforts!

Otherwise, I tried integrating the package in our app and after fixing some issues it seems to work well.
- I fixed two issues in https://github.com/arturgrigor/AppReceiptValidator/pull/1 which you could integrate first

A remaining issue is that the mac tests don't run (for example when selecting the mac demo app scheme and CMD+U), because the remaining Xcode test target is only for iOS. 
Can you find out if there is a way to make a test target be cross platform as well similar to the framework?
Otherwise we could add a dedicated test target again for mac.

Ideally we would also have tests for the SPM version (this would have caught the issue with the missing root certificate for example), so a great addition would be if we would define a testTarget in the manifest.

**Comment by arturgrigor** [comment]
@hannesoid I've fixed the issue for the `AppReceiptValidator Demo macOS` target.

**Comment by arturgrigor** [comment]
@hannesoid I think that there is only one problem left now and that's about the deployment target mismatch between the `AppReceiptValidator` and `OpenSSL` targets on iOS. `OpenSSL` supports iOS 13.4 and later while `AppReceiptValidator` supports iOS 10 and later.

You can see these warnings if you build the framework with the "Any iOS Device" target.

**Comment by hannesoid** [comment]
I think this is already an issue in https://github.com/IdeasOnCanvas/AppReceiptValidator/pull/68, I think we haven't managed to put together an openssl xcframework that works for all platforms/sdks/architectures (tricky: catalyst, ios simulator on apple silicon), and in the process of trying somehow baked in that 13.4.

In my opinion we could go forward and merge this into #68, then can further be discussed there, @weichsel what do you think?

**Comment by arturgrigor** [comment]
@hannesoid I see. If this is the problem then maybe I should bump the deployment target for the `AppReceiptValidator` framework to 13.4 because otherwise it may crash at startup on older devices due to the `OpenSSL` framework. What do you think?

**Comment by hannesoid** [comment]
Yes, you're right, if we don't solve it (or until we do), we should bump the deployment target to 13.4 in Package.swift and framework target / Xcode project. You can include this in this PR if you like.

**Comment by arturgrigor** [comment]
@hannesoid I did the changes but it seems that for the `Package.swift` file you can't set the minor version for the iOS platform using the predefined enum, but you can express it with a `String` but I'm not sure if I should do or need to do that.

**Comment by hannesoid** [comment]
@arturgrigor yes, I also noticed this. Feel free to use the string variant!

**Comment by arturgrigor** [comment]
Ok. Done! From my point of view, I think that this PR is ready to merge.

**Comment by hannesoid** [comment]
great, from my side aswell. I'll still check with @weichsel
- [ ] after merging we can update the package url in the README back to ideasoncanvas

**Comment by weichsel** [comment]
Changes look good to me. I also briefly tested on AS - everything works as expected 👍 

Re. deployment target mismatch between the OpenSSL.xcframework and AppReceiptValidator:
This is a known issue and we should fix that in the base PR.  

Thanks for the changes @arturgrigor!

**Comment by funkenstrahlen** [comment]
@arturgrigor Thank you very much for this contribution! :)

**Comment by funkenstrahlen** [comment]
I just spent some time testing this branch `experiment/openSSLXCFramework` and added `AppReceiptValidator` via SPM to my project.

It works fine when I build for a simulator target. However when I try to *archive* for `Any iOS device` the build fails with this error:

Screen Shot 2020-09-12 at 21 28 35

**Comment by hannesoid** [comment]
@funkenstrahlen @arturgrigor - yes, we unfortunately also noticed this, also when archiving for mac (reverted back to using the framework again)

**Pull request merged**
